### ISSUE TITLE
why the fuck would anyone pay for this shit?

### ISSUE THREAD

**Issue by Were-Logan-0110** [godxgamer/enc_pass#1]

**Comment by godxgamer** [comment]
because you cant make this shit ,
neither you can update this nor reverse this 
 so just shut your fuckin hole

**Comment by Were-Logan-0110** [comment]
> because you cant make this shit , neither you can update this nor reverse this so just shut your fuckin hole

actually i did lmao it's not even hard basically just encryption with a public key from //pwdKeyFetch on mobile and for insta it's basically /shared_data don't think ur special or anything i can make it blindly

**Comment by godxgamer** [comment]
> > because you cant make this shit , neither you can update this nor reverse this so just shut your fuckin hole
> 
> actually i did lmao it's not even hard basically just encryption with a public key from //pwdKeyFetch on mobile and for insta it's basically /shared_data don't think ur special or anything i can make it blindly

now you proved my point "why this shit is paid"
here you only know one encryption version from shared_data 
instagram have 11 different password encryption versions
every key changed from time to time update

anyway i dont care about you 
you are free to make things which you like

**Comment by Were-Logan-0110** [comment]
> > > because you cant make this shit , neither you can update this nor reverse this so just shut your fuckin hole
> > 
> > 
> > actually i did lmao it's not even hard basically just encryption with a public key from //pwdKeyFetch on mobile and for insta it's basically /shared_data don't think ur special or anything i can make it blindly
> 
> now you proved my point "why this shit is paid" here you only know one encryption version from shared_data instagram have 11 different password encryption versions every key changed from time to time update
> 
> anyway i dont care about you you are free to make things which you like

r u mentally okay love?? i mentioned one for insta and one for facebook (//pwd_key_fetch) just to prove the point if u did it any dude if just looked a bit closer will also doit easily it's not even hard do u think following some debugger stack trace or reading some hermes bytecode is much of a big deal making this paid? well anyways i proved my point idgf and i think i'm probably gonna publish the encryptors on my github when i have free time

**Comment by godxgamer** [comment]
> > > > because you cant make this shit , neither you can update this nor reverse this so just shut your fuckin hole
> > > 
> > > 
> > > actually i did lmao it's not even hard basically just encryption with a public key from //pwdKeyFetch on mobile and for insta it's basically /shared_data don't think ur special or anything i can make it blindly
> > 
> > 
> > now you proved my point "why this shit is paid" here you only know one encryption version from shared_data instagram have 11 different password encryption versions every key changed from time to time update
> > anyway i dont care about you you are free to make things which you like
> 
> r u mentally okay love?? i mentioned one for insta and one for facebook (//pwd_key_fetch) just to prove the point if u did it any dude if just looked a bit closer will also doit easily it's not even hard do u think following some debugger stack trace or reading some hermes bytecode is much of a big deal making this paid? well anyways i proved my point idgf and i think i'm probably gonna publish the encryptors on my github when i have free time

then why you just fuck off from here 
i dont care  what you do 

its my code and my choice to make it open source or paid
